development: &default
  adapter: postgresql
  database: admino-example_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: admino-example_test
